services:
  recommend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommend
    restart: always
    networks:
      - munova-net
    environment:
      - PYTHONUNBUFFERED=1
      - KAFKA_CONSUMER_COUNT=10  # Consumer 개수 (초당 1만 처리: 5 -> 10)
    volumes:
      - .:/app
    ports:
      - "8001:8001"  # FastAPI 서버 포트
      - "9000:9000"  # Kafka Consumer-0 Prometheus metrics
      - "9001:9001"  # Kafka Consumer-1 Prometheus metrics
      - "9002:9002"  # Kafka Consumer-2 Prometheus metrics
      - "9003:9003"  # Kafka Consumer-3 Prometheus metrics
      - "9004:9004"  # Kafka Consumer-4 Prometheus metrics
      - "9005:9005"  # Kafka Consumer-5 Prometheus metrics
      - "9006:9006"  # Kafka Consumer-6 Prometheus metrics
      - "9007:9007"  # Kafka Consumer-7 Prometheus metrics
      - "9008:9008"  # Kafka Consumer-8 Prometheus metrics
      - "9009:9009"  # Kafka Consumer-9 Prometheus metrics

    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.2
    container_name: recommend-mongodb
    restart: always
    networks:
      - munova-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=recommend
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --wiredTigerCacheSizeGB 1

volumes:
  mongodb_data:
  mongodb_config:

networks:
  munova-net:
    external: true
