# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_action_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user_action_log.proto\x12\x1a\x63om.space.munova.log.proto\"\x9b\x01\n\rUserActionLog\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x11\n\tmember_id\x18\x03 \x01(\x03\x12\x11\n\tdata_json\x18\x04 \x01(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x05 \x01(\x03\x12\x15\n\rproducer_time\x18\x06 \x01(\x03\x12\x0f\n\x07version\x18\x07 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_action_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERACTIONLOG._serialized_start=54
  _USERACTIONLOG._serialized_end=209
# @@protoc_insertion_point(module_scope)
